### PR TITLE
Update metadata, proto and change code to follow https://github.com/googlei18n/libphonenumber

### PR DESCRIPTION
**Pull request by bennyscetbun**
Update metadata
Update proto 
Change code to follow https://github.com/googlei18n/libphonenumber new way to coerce phonenumber
Add a makefile to ease proto and metadata update

---
This change is [Reviewable](https://reviewable.io/reviews/ttacon/libphonenumber/51)

### CODE REVIEW

**Comment by ttacon** [comment]
Hey @bennyscetbun, can you squash these? I updated the build system and I'd like to see this rebuild (some tests failed for me locally?) Thanks! Excited to get this PR merged!

**Comment by bennyscetbun** [comment]
Squashed :)

**Comment by bennyscetbun** [comment]
\o/

**Comment by bennyscetbun** [comment]
Hey ttacon.
I just found out that you ve remove me as the author of the commit.
It seems to be an error :)
Could you change that?
Thanks

**Comment by ttacon** [comment]
Ah, that's just a GitHub visual affect. If you look at the merge commit/PR (i.e. [here](https://github.com/ttacon/libphonenumber/pull/53)), you're still the author, I just merged it.

**Comment by bennyscetbun** [comment]
image
this is from tig command after a git clone :)

**Comment by bennyscetbun** [comment]
If you could fix that, that would be greatly appreciate :)

**Pull request merged**
