### PR TITLE
Fix a bug raised in issue #32

### PR DESCRIPTION
**Pull request by jvictorchen**
See #32 for more details

---
This change is [Reviewable](https://reviewable.io/reviews/ttacon/libphonenumber/34)

### CODE REVIEW

**Comment by ttacon** [comment]
Awesome! Thanks for the PR! Could you also add a test for `testNumberLengthAgainstPattern` itself?

**Comment by jvictorchen** [comment]
Tests added :)

**Comment by ttacon** [comment]
ty for the PR!

**Comment by jvictorchen** [comment]
Thanks for accepting the PR!

**Pull request merged**
